refactor(web/test): V2BakeryControllerWithClouddriverServiceTest cleanup (#979)
* refactor(web/test): remove unused variables from V2BakeryControllerWithClouddriverServiceTest

* refactor(test/web): use com.github.tomakehurst:wiremock-jre8-standalone instead of com.github.tomakehurst:wiremock-jre8

to reduce dependencies, but also to pick up a newer version

snippet of $ ./gradlew rosco-web:dependencies --configuration testCompileClasspath before:

\--- com.github.tomakehurst:wiremock-jre8 -> 2.26.3
     +--- org.eclipse.jetty:jetty-server:9.4.20.v20190813 -> 9.4.46.v20220331
     |    +--- javax.servlet:javax.servlet-api:3.1.0 -> 4.0.1
     |    +--- org.eclipse.jetty:jetty-http:9.4.46.v20220331
     |    |    +--- org.eclipse.jetty:jetty-util:9.4.46.v20220331
     |    |    \--- org.eclipse.jetty:jetty-io:9.4.46.v20220331
     |    |         \--- org.eclipse.jetty:jetty-util:9.4.46.v20220331
     |    \--- org.eclipse.jetty:jetty-io:9.4.46.v20220331 (*)
     +--- org.eclipse.jetty:jetty-servlet:9.4.20.v20190813 -> 9.4.46.v20220331
     |    +--- org.eclipse.jetty:jetty-security:9.4.46.v20220331
     |    |    \--- org.eclipse.jetty:jetty-server:9.4.46.v20220331 (*)
     |    \--- org.eclipse.jetty:jetty-util-ajax:9.4.46.v20220331
     |         \--- org.eclipse.jetty:jetty-util:9.4.46.v20220331
     +--- org.eclipse.jetty:jetty-servlets:9.4.20.v20190813 -> 9.4.46.v20220331
     |    +--- org.eclipse.jetty:jetty-continuation:9.4.46.v20220331
     |    +--- org.eclipse.jetty:jetty-http:9.4.46.v20220331 (*)
     |    +--- org.eclipse.jetty:jetty-util:9.4.46.v20220331
     |    \--- org.eclipse.jetty:jetty-io:9.4.46.v20220331 (*)
     +--- org.eclipse.jetty:jetty-webapp:9.4.20.v20190813 -> 9.4.46.v20220331
     |    +--- org.eclipse.jetty:jetty-xml:9.4.46.v20220331
     |    |    \--- org.eclipse.jetty:jetty-util:9.4.46.v20220331
     |    \--- org.eclipse.jetty:jetty-servlet:9.4.46.v20220331 (*)
     +--- com.google.guava:guava:27.0.1-jre -> 30.0-jre (*)
     +--- com.fasterxml.jackson.core:jackson-core:2.10.0 -> 2.12.7 (*)
     +--- com.fasterxml.jackson.core:jackson-annotations:2.10.0 -> 2.12.7 (*)
     +--- com.fasterxml.jackson.core:jackson-databind:2.10.0 -> 2.12.7.1 (*)
     +--- org.apache.httpcomponents:httpclient:4.5.6 -> 4.5.13
     |    +--- org.apache.httpcomponents:httpcore:4.4.13 -> 4.4.15
     |    \--- commons-codec:commons-codec:1.11 -> 1.15
     +--- org.xmlunit:xmlunit-core:2.6.2 -> 2.8.4
     +--- org.xmlunit:xmlunit-legacy:2.6.2 -> 2.8.4
     |    \--- org.xmlunit:xmlunit-core:2.8.4
     +--- org.xmlunit:xmlunit-placeholders:2.6.2 -> 2.8.4
     |    \--- org.xmlunit:xmlunit-core:2.8.4
     +--- com.jayway.jsonpath:json-path:2.4.0 -> 2.5.0 (*)
     +--- org.ow2.asm:asm:7.0 -> 8.0.1
     +--- org.slf4j:slf4j-api:1.7.12 -> 1.7.36
     +--- net.sf.jopt-simple:jopt-simple:5.0.3
     +--- org.apache.commons:commons-lang3:3.7 -> 3.12.0
     +--- com.github.jknack:handlebars:4.1.2
     |    \--- org.slf4j:slf4j-api:1.7.25 -> 1.7.36
     +--- com.github.jknack:handlebars-helpers:4.1.2
     |    +--- com.github.jknack:handlebars:4.1.2 (*)
     |    \--- org.apache.commons:commons-lang3:3.8.1 -> 3.12.0
     +--- com.flipkart.zjsonpatch:zjsonpatch:0.4.4
     +--- commons-fileupload:commons-fileupload:1.4
     |    \--- commons-io:commons-io:2.2 -> 2.11.0
     +--- org.eclipse.jetty.http2:http2-server:9.4.20.v20190813 -> 9.4.46.v20220331
     |    +--- org.eclipse.jetty.http2:http2-common:9.4.46.v20220331
     |    |    \--- org.eclipse.jetty.http2:http2-hpack:9.4.46.v20220331
     |    |         +--- org.eclipse.jetty:jetty-util:9.4.46.v20220331
     |    |         +--- org.eclipse.jetty:jetty-http:9.4.46.v20220331 (*)
     |    |         \--- org.eclipse.jetty:jetty-io:9.4.46.v20220331 (*)
     |    \--- org.eclipse.jetty:jetty-server:9.4.46.v20220331 (*)
     +--- org.eclipse.jetty:jetty-alpn-server:9.4.20.v20190813 -> 9.4.46.v20220331
     |    \--- org.eclipse.jetty:jetty-server:9.4.46.v20220331 (*)
     +--- org.eclipse.jetty:jetty-alpn-conscrypt-server:9.4.20.v20190813 -> 9.4.46.v20220331
     |    +--- org.conscrypt:conscrypt-openjdk-uber:2.5.2
     |    +--- org.eclipse.jetty:jetty-alpn-server:9.4.46.v20220331 (*)
     |    \--- org.eclipse.jetty:jetty-io:9.4.46.v20220331 (*)
     +--- org.eclipse.jetty:jetty-alpn-conscrypt-client:9.4.20.v20190813 -> 9.4.46.v20220331
     |    +--- org.conscrypt:conscrypt-openjdk-uber:2.5.2
     |    \--- org.eclipse.jetty:jetty-alpn-client:9.4.46.v20220331
     |         \--- org.eclipse.jetty:jetty-io:9.4.46.v20220331 (*)
     \--- net.javacrumbs.json-unit:json-unit-core:2.12.0
          +--- org.opentest4j:opentest4j:1.1.1 -> 1.2.0
          \--- org.hamcrest:hamcrest-core:2.1 -> 2.2 (*)

after:

\--- com.github.tomakehurst:wiremock-jre8-standalone -> 2.31.0

* fix(web/test): mock the BakePoller in

to avoid multiple long stack traces in test output similar to

2023-04-06 17:14:20.946 ERROR 56717 --- [RxIoScheduler-5] c.n.spinnaker.rosco.executor.BakePoller  : Zombie Killer Polling Error:

redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.util.Pool.getResource(Pool.java:84) ~[jedis-3.6.3.jar:na]
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:370) ~[jedis-3.6.3.jar:na]
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:15) ~[jedis-3.6.3.jar:na]
	at com.netflix.spinnaker.kork.jedis.JedisClientDelegate.withKeyScan(JedisClientDelegate.java:180) ~[kork-jedis-7.171.2.jar:7.171.2]
	at com.netflix.spinnaker.rosco.persistence.RedisBackedBakeStore.scanIncompleteBakesKeys(RedisBackedBakeStore.groovy:584) ~[rosco-core.jar:na]
	at com.netflix.spinnaker.rosco.persistence.RedisBackedBakeStore.getAllIncompleteBakeIds(RedisBackedBakeStore.groovy:538) ~[rosco-core.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.15.jar:2.5.15]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.15.jar:2.5.15]
	at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProperty.java:76) ~[groovy-2.5.15.jar:2.5.15]
	at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.callGetProperty(GetEffectivePogoPropertySite.java:48) ~[groovy-2.5.15.jar:2.5.15]
	at com.netflix.spinnaker.rosco.executor.BakePoller$_onApplicationEvent_closure2.doCall(BakePoller.groovy:106) ~[rosco-core.jar:na]
	at com.netflix.spinnaker.rosco.executor.BakePoller$_onApplicationEvent_closure2.doCall(BakePoller.groovy) ~[rosco-core.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.15.jar:2.5.15]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.15.jar:2.5.15]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.15.jar:2.5.15]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.15.jar:2.5.15]
	at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.15.jar:2.5.15]
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50) ~[groovy-2.5.15.jar:2.5.15]
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:122) ~[groovy-2.5.15.jar:2.5.15]
	at com.sun.proxy.$Proxy198.call(Unknown Source) ~[na:na]
	at rx.internal.schedulers.SchedulePeriodicHelper$1.call(SchedulePeriodicHelper.java:72) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) ~[rxjava-1.3.8.jar:1.3.8]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed to create socket.
	at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:110) ~[jedis-3.6.3.jar:na]
	at redis.clients.jedis.Connection.connect(Connection.java:226) ~[jedis-3.6.3.jar:na]
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:135) ~[jedis-3.6.3.jar:na]
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:309) ~[jedis-3.6.3.jar:na]
	at redis.clients.jedis.BinaryJedis.initializeFromClientConfig(BinaryJedis.java:87) ~[jedis-3.6.3.jar:na]
	at redis.clients.jedis.BinaryJedis.<init>(BinaryJedis.java:292) ~[jedis-3.6.3.jar:na]
	at redis.clients.jedis.Jedis.<init>(Jedis.java:167) ~[jedis-3.6.3.jar:na]
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:177) ~[jedis-3.6.3.jar:na]
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:918) ~[commons-pool2-2.9.0.jar:2.9.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:431) ~[commons-pool2-2.9.0.jar:2.9.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:356) ~[commons-pool2-2.9.0.jar:2.9.0]
	at redis.clients.jedis.util.Pool.getResource(Pool.java:75) ~[jedis-3.6.3.jar:na]
	... 36 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:609) ~[na:na]
	at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:80) ~[jedis-3.6.3.jar:na]
	... 47 common frames omitted

* refactor(web/test): use dynamic port in V2BakeryControllerWithClouddriverServiceTest

to avoid possible conflicts with fixed ports